# =================================================================================================
#     Input Data
# =================================================================================================

# Set the input data, using file paths relative to the main snakemake directory
data:

  # Input table that lists all samples with their units and fastq files.
  samples: "samples.tsv"

  reference:

    # Name of the reference genome. This has to be a valid snpeff database genome name.
    name: "Arabidopsis_thaliana"

    # Path to the reference genome, using the file ideally as it is provided by the GATK bundle.
    genome: "../ath-evo-ref/TAIR10_chr_all.fa"

    # Path to any database of known variants, ideally as it is provided by the GATK bundle.
    # If no such file is available, use an empty list or string instead.
    known-variants: "/Carnegie/DPB/Data/Shared/Labs/Moi/Everyone/1001g/vcf/1001genomes_snp-short-indel_only_ACGTN.vcf.gz"

# =================================================================================================
#     Pipeline Settings
# =================================================================================================

settings:

  # Select whether to mark and remove duplicates after mapping, using picard/markduplicates
  remove-duplicates: true

  # Select whether to recalibrate base frequencies after mapping, using gatk/baserecalibrator
  recalibrate-base-qualities: false

  # Select the tool used for read trimming.
  # Valid values: "trimmomatic", "skewer"
  trimming-tool: "skewer"

  # Select the tool used for read mapping.
  # Valid values: "bwamem", "bowtie2"
  mapping-tool: "bwamem"

  # Select the tool used for SNP calling.
  # Valid values: "haplotypecaller", "bcftools", "freebayes"
  calling-tool: "haplotypecaller"

  # Uncomment and point to a bed file with, e.g., captured regions if necessary,
  # see https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals
  # restrict-regions: captured_regions.bed

  # If regions are restricted, uncomment this to enlarge them by the given value
  # in order to include flanking areas.
  # region-padding: 100

  # Set to true in order to apply machine learning based recalibration
  # of quality scores instead of hard filtering.
  vqsr: false

# =================================================================================================
#     Tool Parameters
# =================================================================================================

params:

  # ----------------------------------------------------------------------
  #     trimmomatic
  # ----------------------------------------------------------------------

  trimmomatic:
    threads: 6
    pe:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
    se:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"

  # ----------------------------------------------------------------------
  #     skewer
  # ----------------------------------------------------------------------

  skewer:
    threads: 6
    se: "--mode any"
    pe: "--mode pe"

  # ----------------------------------------------------------------------
  #     bwa mem
  # ----------------------------------------------------------------------

  # Used only if settings:mapping-tool == bwamem
  bwamem:
    threads: 6

  # ----------------------------------------------------------------------
  #     bowtie2
  # ----------------------------------------------------------------------

  # Used only if settings:mapping-tool == bowtie2
  bowtie2:
    threads: 6

  # ----------------------------------------------------------------------
  #     picard
  # ----------------------------------------------------------------------

  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"

  # ----------------------------------------------------------------------
  #     bcftools
  # ----------------------------------------------------------------------

  # Used only if settings:calling-tool == bcftools
  bcftools:
    mpileup: "--max-depth 10000"
    call: ""
    threads: 6
    # concat: ""

  # ----------------------------------------------------------------------
  #     freebayes
  # ----------------------------------------------------------------------

  # Used only if settings:calling-tool == freebayes
  freebayes:
    extra: ""
    chunksize: 100000
    threads: 4
    compress-threads: 2

  # ----------------------------------------------------------------------
  #     gatk
  # ----------------------------------------------------------------------

  gatk:
    # Used only if settings:recalibrate-base-qualities == true
    BaseRecalibrator: ""

    # Used only if settings:calling-tool == haplotypecaller
    HaplotypeCaller: ""
    HaplotypeCaller-threads: 2
    GenotypeGVCFs: ""

    # Used only if settings:vqsr == true
    VariantRecalibrator: ""

  # ----------------------------------------------------------------------
  #     gatk / variantfiltration
  # ----------------------------------------------------------------------

  # Used only if settings:vqsr == false
  variantfiltration-hard:
    # Hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"
